name: aud_for_bank
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  firebase_core: ^3.12.1
  firebase_database: ^11.3.4
  firebase_messaging: ^15.2.4
  flutter:
    sdk: flutter
  http: ^1.3.0
  mjpeg_stream: ^1.0.1
  shared_preferences: ^2.5.2
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  video_player: ^2.9.3


dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true

